steps:
  - name: test
    image: hexpm/elixir:1.19.5-erlang-27.3-ubuntu-noble-20260113
    commands:
      - apt-get update && apt-get install -y curl build-essential
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . $HOME/.cargo/env
      - cd apps/minutemodem_core
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix compile